name: Build and Publish Docker Image

on:
  # Run on all pushes (no branch filter)
  push:
    # Also run on version tags
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:  # Allow manual triggering

env:
  # Use github.repository as the name of the image, converted to lowercase
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup Docker buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Extract version from package.json and prepare repository name
      - name: Extract version and prepare repository name
        id: package-version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Extracted version: $VERSION"
          
          # Convert repository name to lowercase for Docker compatibility
          REPO_LOWERCASE=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          echo "REPO_LOWERCASE=$REPO_LOWERCASE" >> $GITHUB_ENV
          echo "Repository name (lowercase): $REPO_LOWERCASE"

      # Login to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push Docker image
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ env.REPO_LOWERCASE }}:latest
            ghcr.io/${{ env.REPO_LOWERCASE }}:${{ env.VERSION }}
          cache-from: type=gha
          cache-to: type=gha,mode=max